// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['connections']['Connection']['Close']();
}

export function Connect(arg1, arg2) {
  return window['go']['connections']['Connection']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['connections']['Connection']['Disconnect']();
}

export function GetConnection() {
  return window['go']['connections']['Connection']['GetConnection']();
}

export function GetConnectionInfo() {
  return window['go']['connections']['Connection']['GetConnectionInfo']();
}

export function GetConnectionType() {
  return window['go']['connections']['Connection']['GetConnectionType']();
}

export function TestConnection(arg1, arg2) {
  return window['go']['connections']['Connection']['TestConnection'](arg1, arg2);
}
