// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close():Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<void>;

export function GetConnection():Promise<any>;

export function GetConnectionType():Promise<string>;

export function TestConnection(arg1:string,arg2:string):Promise<boolean>;
