// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1) {
  return window['go']['queries']['Query']['Run'](arg1);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['queries']['Query']['SaveConnection'](arg1, arg2);
}

export function TestConnection(arg1, arg2) {
  return window['go']['queries']['Query']['TestConnection'](arg1, arg2);
}
