// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run(arg1:string):Promise<any>;

export function SaveConnection(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<boolean>;
